### PR TITLE
Switch back to a venv for docs + fix .circle config

### PR DESCRIPTION
**Pull request by yuvipanda**
- [x] Add tests

### CODE REVIEW

**Comment by yuvipanda** [comment]
Looks like there was a conflict in #124, which seems to have added an environment.yml file for docs and maybe removed the docs-requirement.txt file that the documentation integration test was looking for. Since there wasn't anything hard to do with pip in the environment.yml file, I've moved it back to requirements.txt file since it's easier to do that than try to convert the integration test container to have conda :)

**Comment by choldgraf** [comment]
yo - I mostly copied over the environment.yml file because it was used in the other jupyterhub projects, and since it was the only way I could figure out how to get RTD builds working (but perhaps we can point the `.readthedocs` config file to the `pip` file instead). I'll try to take a look at it on my flight.

**Comment by choldgraf** [comment]
Also - note that my intention was actually to use both environment.yml and a requirements.txt file. It's just that this is wrapped up in the still-unmerged PR from Zexuan's user test:

https://github.com/jupyterhub/the-littlest-jupyterhub/pull/123/files#diff-b0278a395ac6448087984d5186dbe855R9

**Pull request merged**
