### PR TITLE
adding documentation for GitHub OAuth

### LINKED ISSUE #98: Add a detailed tutorial on the GitHub authenticator
GitHub is a really common tool that users of TLJH will probably also use.

### PR DESCRIPTION
**Pull request by choldgraf**
- [x] Add / update documentation
 - [ ] Add tests

This adds instructions for setting up the GitHub authenticator with TLJH.

closes #98 

cc @jzf2101

### CODE REVIEW

**Comment by jzf2101** [comment]
How do you plan on adding tests? Can we just merge?

**Comment by choldgraf** [comment]
I think so, I'm not sure if this is testable or not. WDYT @yuvipanda ?

**Comment by yuvipanda** [comment]
Yeah, I think we can't add automated tests for these. Let's merge!

**Comment by jzf2101** [comment]
Cool can we take out that item from the PR notes?

**Comment by choldgraf** [comment]
done

**Pull request merged**
