### PR TITLE
Change style to match Jhub main doc

### PR DESCRIPTION
**Pull request by leportella**
- [X] Add / update documentation
 - [ ] Add tests

 

I change a bit the style to match the JupyterHub main documentation (removed the Github banner, added logo and favicon) and shortened the project name so it doesn't "brake".

Before:
Screen Shot 2019-04-13 at 20 22 24

After:
Screen Shot 2019-04-13 at 20 22 32

### CODE REVIEW

**Comment by yuvipanda** [comment]
I like it! I wanna keep the 'The Littlest JupyterHub' there fully though. Do you think we can reduce the title size instead?

**Comment by leportella** [comment]
I tried to find something, but couldn't. If anyone have an ideia, I am open to suggestions. Otherwise, we can just add the logo and keep the long name.

**Comment by yuvipanda** [comment]
@leportella yeah, I think let's just keep the long name in this PR, and change it later?

**Comment by leportella** [comment]
done @yuvipanda

**Comment by yuvipanda** [comment]
@leportella awesome! merged :) Thank you!

**Pull request merged**
