### PR TITLE
Upgrade to Jupyterlab 3.0 and Jupyter Resource Usage

### PR DESCRIPTION
**Pull request by jtpio**
Replaces #647 with the suggested changes.

- [x] Update to JupyterLab 3.0
- [x] Update from `nbresuse` to Jupyter Resource Usage: https://github.com/jupyter-server/jupyter-resource-usage
- [x] Add / update documentation
- [ ] Add tests

### CODE REVIEW

**Comment by jtpio** [comment]
cc @astrojuanlu if you are able to test this branch, which also removes Node.js from the install.

**Comment by astrojuanlu** [comment]
On it!

**Comment by jtpio** [comment]
Pushed one more change to update from `nbresuse` to `jupyter-resource-usage` (which includes a prebuilt extension for JupyterLab 3.0).

**Comment by astrojuanlu** [comment]
Tested on an Ubuntu 20.04 virtual machine w/ Firefox, works like a charm 🚀

**Comment by jtpio** [comment]
Nice, thanks for testing!

Need to check what's going on with the tests to make it ready for review soon.

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/deploy-jupyterhub-3-in-tljh/7801/5

**Comment by yuvipanda** [comment]
Restarting the build fix the unit test, because we don't pin chardet properly. Thanks for getting this over the line, @jtpio :)

**Pull request merged**
