### PR TITLE
Add a how-to guide on selecting VM Memory / CPU / Disk size

### PR DESCRIPTION
**Pull request by yuvipanda**
Ref #57, #56, and #48

### CODE REVIEW

**Comment by yuvipanda** [comment]
@geoffbacon @norcalbiostat There's now more docs on this at https://the-littlest-jupyterhub.readthedocs.io/en/latest/howto/resource-estimation.html. Would love feedback on how it reads :)

**Comment by geoffbacon** [comment]
Yeah, this is really useful! One minor suggestion I have is to provide a hint on how to estimate memory usage for a single user. Even just linking to something like [this](https://timothymonteath.com/monitoring-memory-usage-in-jupyter-notebooks/) .

**Comment by yuvipanda** [comment]
@geoffbacon awesome! I think I'll add nbresuse instead...

**Comment by geoffbacon** [comment]
:+1:

**Comment by norcalbiostat** [comment]
Looks great, thank you!

**Pull request merged**
