### PR TITLE
ci: run int. and unit tests on 22.04 LTS + py3.10

### PR DESCRIPTION
**Pull request by MridulS**
I tried to install tljh 22.04 on a clean digital ocean machine with Ubuntu 22.04 LTS and it worked without any issues!

Just trying to run the tests to see if there are any failures with the 22.04 + py3.10 combo.

Maybe we can close https://github.com/jupyterhub/the-littlest-jupyterhub/issues/714 if this passes?

### CODE REVIEW

**Comment by wjcapehart** [comment]
> I tried to install tljh 22.04 on a clean digital ocean machine with Ubuntu 22.04 LTS and it worked without any issues!
> 
> 
> 
> Just trying to run the tests to see if there are any failures with the 22.04 + py3.10 combo.
> 
> 
> 
> Maybe we can close https://github.com/jupyterhub/the-littlest-jupyterhub/issues/714 if this passes?

My machine was an upgrade from 20.04 LTS to 22.04 LTS, not a clean fresh build.

Bill

**Comment by MridulS** [comment]
The test failures are due to `ubuntu-22.04` not being "released" properly I think, docker seems to be missing from the environment https://github.com/actions/virtual-environments/issues/5490

**Comment by consideRatio** [comment]
@MridulS thanks! I'd like to drop testing against 21.10 as part of testing against 22.04. I wanted to add 21.10 as a step towards getting it to function in 22.04 when that was released, rather than test against that and other half year releases.

**Comment by consideRatio** [comment]
I cleaned up the git history in this PR and pushed one commit besides the first one you had. I figure if we are to sort out the test failures (#830). Let's start from this situation when we test against 18.04, 20.04, 22.04 and go from there.

**Pull request merged**
