### PR TITLE
Use newer firstuseauthenticator

### PR DESCRIPTION
**Pull request by willirath**
This uses v0.12 which allow for deleting users before they have set their password.

 - [ ] Add / update documentation
 - [ ] Add tests

Is any of the above necessary?

### CODE REVIEW

**Comment by yuvipanda** [comment]
@willirath I think that's ok for this PR.

Would you like merge rights on this repo too? :)

**Comment by yuvipanda** [comment]
Test failure is unrelated, and needs to be sorted out separately.

**Comment by willirath** [comment]
> Would you like merge rights on this repo too? :)

Sure. This would go together nicely with what I'm doing over the next few weeks / months.

**Comment by yuvipanda** [comment]
@willirath done!

**Comment by willirath** [comment]
Thanks! 


Am 26. Januar 2019 04:05:07 schrieb Yuvi Panda <notifications@github.com>:

**Pull request merged**
