### PR TITLE
Upgrade to JupyterHub 1.0

### PR DESCRIPTION
**Pull request by minrk**
bump oauthenticator patch as well

### CODE REVIEW

**Comment by yuvipanda** [comment]
@minrk awesome! Do you think we should put upgrade-db in pre-start for JupyterHub service here, similar to what we do in z2jh?

**Comment by minrk** [comment]
Yeah, that's a good idea.

**Comment by yuvipanda** [comment]
@minrk let me know if my change looks good

**Comment by yuvipanda** [comment]
Not sure yet why this is failing.

**Comment by minrk** [comment]
Debugging the integration tests can be hard, since we get little feedback about the errors. It would be good to show logs on failure. I'll look into it today.

**Comment by yuvipanda** [comment]
@minrk did you manage to find any time to look into this?

**Comment by yuvipanda** [comment]
Instead of using pre-start, I have instead passed --upgrade-db to the JupyterHub process itself. This matches what we do in z2jh.

**Comment by yuvipanda** [comment]
Tests pass, yay!

**Comment by yuvipanda** [comment]
I'll merge this one now :)

**Pull request merged**
