### PR TITLE
Add more validation to bootstrap.py

### PR DESCRIPTION
**Pull request by yuvipanda**
- Check for Python Version
- Check if systemd is present
- Provide more useful error message when running inside
  an unprepared docker container

Ref #16

 - [ ] Add / update documentation
 - [x] Add tests

### CODE REVIEW

**Comment by yuvipanda** [comment]
Docs on docker container in #333. This still needs tests though.

**Comment by yuvipanda** [comment]
Test added. I'm curious about the wording. I'm not sure 'plain' docker container is quite right.

**Comment by betatim** [comment]
Not quite sure what it means to run in "plain docker". It makes me think that this is using a version of docker that hasn't been modified. As in the "plain" refers to dockerd, not the image that we are using (which is what I think this is about).

Could it be named "no-systemd-docker"?

**Comment by yuvipanda** [comment]
@betatim updated to refer to 'docker container without systemd' instead.

**Pull request merged**
