### PR TITLE
pre-commit: apply black formatting (and prettier on one yaml file)

### PR DESCRIPTION
**Pull request by consideRatio**
I've applied black formatting now. I ran it once first without string normalization, applied some manual tweaks, and then ran it with string normalization.

String normalization isn't systematically used with black in the jupyterhub org. I personally favor it though and figure it could make sense to do while also applying black in the first place - something that is reasonable to do only when the amount of PRs are low.

### CODE REVIEW

**Comment by consideRatio** [comment]
@manics @yuvipanda @choldgraf what do you think?

The PR list is down from 20 to 1 single stale PR with very little changes, can we go for a full `black` CLI transform at this point?

Waiting for this to get merged is somewhat of a blocker to start doing more work as well.

image

**Review by choldgraf — APPROVED** [review]
I'm +1 on merging this - the remaining PR isn't complicated enough that it would be majorly disrupted by this. I think it'd be OK to merge so that we don't start to create conflicts when new PRs come up

**Review by manics — APPROVED** [review]
LGTM!

**Comment by consideRatio** [comment]
Thanks @manics @choldgraf! I'll go for a merge

**Pull request merged**
