### PR TITLE
Provide better error message when running on unsupported distro

### LINKED ISSUE #186: Won't install on Ubuntu 16.04
I'm trying to install tljh in Ubuntu 16.04, but I get the following error:

    Checking if TLJH is already installed...
    TLJH already installed, upgrading...
    Upgrading TLJH installer...
    Setup tljh package
    Starting TLJH installer...
    Traceback (most recent call last):
      File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/usr/lib/python3.5/runpy.py", line 144, in _get_module_details
        code = loader.get_code(mod_name)
      File "<frozen importlib._bootstrap_external>", line 767, in get_code
      File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/opt/tljh/hub/lib/python3.5/site-packages/tljh/installer.py", line 326
        raise FileExistsError(f'/usr/bin/tljh-config exists but is not a symlink to {tljh_config_src}')
                                                                                                 ^
    SyntaxError: invalid syntax

I see that the offending line uses a string feature ('f' prefix) that is not available in python 3.5, which is the most recent python in Ubuntu 16.04.

### PR DESCRIPTION
**Pull request by yuvipanda**
- [x] Add / update documentation
 - [x] Add tests

Fixes #186 #206

### CODE REVIEW

**Comment by yuvipanda** [comment]
This provides a better error message, and bolder text about requiring Ubuntu 18.04.

**Comment by Carreau** [comment]
I believe platform will be removed from stdlib in 3.8. I need to check.

**Comment by choldgraf** [comment]
ahh yea, on

https://docs.python.org/2/library/platform.html#platform.linux_distribution

I see:

```
Note This function is deprecated since Python 3.5 and removed in Python 3.8. See alternative like the distro package.
```

looks like the usage for "distro" is pretty similar:

https://pypi.org/project/distro/

**Comment by yuvipanda** [comment]
Unfortunately we have to only use stdlib in bootstrap.py. I'll probably switch it to read from /etc/os-release. Thanks for the pointer, @carreau and @choldgraf

**Comment by yuvipanda** [comment]
@Carreau @choldgraf I've modified this to use /etc/os-release now!

**Comment by choldgraf** [comment]
is this ready to go now?

**Comment by Carreau** [comment]
Awayyyyy we go.

**Pull request merged**
