### PR TITLE
add -L option to curl to follow redirect

### PR DESCRIPTION
**Pull request by LTangaF**
to new bootstrap location

 - [ ] Add / update documentation
 - [ ] Add tests

### CODE REVIEW

**Comment by LTangaF** [comment]
This is a minor documentation fix. Not sure how testable that is from an automated perspective. I tested it in AWS, though.

**Comment by LTangaF** [comment]
I didn't realize there was a test for the documentation changes. It looks like it came up green here without it, which is interesting.

I'll work on those other doc changes.

**Comment by GeorgianaElena** [comment]
> I didn't realize there was a test for the documentation changes. It looks like it came up green here without it, which is interesting.

There isn't any test for doc changes that would error from this. I think the red from my `grep` command output was misleading. Sorry for that.

> I'll work on those other doc changes.

Thanks a lot for working on this :heart:

**Comment by LTangaF** [comment]
I updated the integration test as well.

**Pull request merged**
