### PR TITLE
Add changelog for 1.0.0b1

### PR DESCRIPTION
**Pull request by consideRatio**
I propose we make a 1.0.0b1 release ~today (July 6th 2023)! I know there are at least a few users very interested in getting a release out based on comments in issues. I'm going on vacation next week, and really hope to have a beta release out by then. I have a lot of other things I need to do by then as well, so I'm extremely thankful for all help to get this pre-release out.

## Action points

- This changelog includes the PR #924 that should get merged before the 1.0.0b1 pre-release

## Action points that maybe doesn't block a 1.0.0b1 release

- [ ] There should ideally be notes to link to from the changelog on how to make an upgrade and what to think about when doing one
  - #81 

## Related

- #873

## Changelog preview

See it at [RTD PR build[(https://the-littlest-jupyterhub--888.org.readthedocs.build/en/888/reference/changelog.html), here is a screenshot.

image

### CODE REVIEW

**Comment by consideRatio** [comment]
Hmmm, I think maybe we want:
- #81 
- Link to the result of #81 from the changelog or write in it that one is expected to run the bootstrap.py script as fetched from the internet.

**Review by nsurleraux-railnova — APPROVED** [review]
Great work! It still needs documentation about the upgrading process, especially about upgrading user env libs and making a backup if the upgrade borks the user env.

**Comment by nsurleraux-railnova** [comment]
> When you write "about upgrading user env libs", what are you thinking about more specifically? I'm thinking that this upgrade should not need to be associated with upgrading the user env in any way, and that users should manage that independently on this upgrade being made.

In your changelog, you are including a table named`Dependency changes in the user environment`, which may lead to think that they are part of the automated upgrade process. But the code specifies that they won't be upgraded. I would like to see in the documentation of the upgrade process:
- Backup your `/opt/tljh/user` folder.
- Run `/opt/tljh/user/bin/pip install jupyterhub==4.x.x`

Or something similar...

Another option could be to have an option in the upgrade process (maybe `--upgrade-user-env`) that will reinstall the user env dependencies from https://github.com/jupyterhub/the-littlest-jupyterhub/blob/main/tljh/requirements-user-env-extras.txt. It should be pretty clear in the documentation that a backup is always necessary or the upgrade process should automatically backup the user env...

**Comment by nsurleraux-railnova** [comment]
Hi @consideRatio,

Will the first release of 1.0.0 be a beta version since you changed the version tag to 1.0.0b1? What motived this change of direction?

**Comment by consideRatio** [comment]
@nsurleraux-railnova yes making an initial beta release is the current proposal. I made a proposal for 1.0.0 before because I didn't understand it was technically possible for this project to make make a beta release until yesterday via https://github.com/jupyterhub/the-littlest-jupyterhub/issues/909#issuecomment-1621892582.

**Comment by nsurleraux-railnova** [comment]
Ok! Should we then consider this beta as not production ready?

**Review by minrk — APPROVED** [review]

**Comment by consideRatio** [comment]
Thanks @minrk!!

**Pull request merged**
