### PR TITLE
Issue#182: add amazon installation tutorial

### PR DESCRIPTION
**Pull request by fomightez**
- [x] Add documentation amazon installation tutorial, in relation to issue #182 

plus, fixed one typo in google installation documentation

### CODE REVIEW

**Comment by willingc** [comment]
@fomightez Thought you may have a use for the presentation that your contribution inspired: https://docs.google.com/presentation/d/1w3TyVTkZD-63ZX28rg7JzbHBIX22JXH4cryAhrH5oHw/edit?usp=sharing

**Comment by fomightez** [comment]
@willingc Thanks for sharing that. I hope it at least saved you some time since I had recently gone through the process. They didn't even have Ubuntu 18.04 alone in the standard AMIs when I first tried it. Plus I was glad to learn the free tier worked.

**Comment by willingc** [comment]
@fomightez It did save me a ton of time :D Great job contributing back to the project too.

**Comment by jzf2101** [comment]
@go-bears does this work with you too?

**Pull request merged**
