### PR TITLE
adding update on resizing droplet

### PR DESCRIPTION
**Pull request by wrightaprilm**
- [ x ] Add / update documentation
 - [ ] Add tests

Hello, I added a segment to the [Digital Ocean set-up instruction](https://the-littlest-jupyterhub.readthedocs.io/en/latest/install/digitalocean.html) on resizing a droplet. These instructions are definitely not brought to you by resizing a droplet, and then forgetting to update the config and wondering why my mem was so low ;) Because this update is so basic, you might consider it to be out-of-scope for the documentation. 

I wasn't able to perform this:
``
advpng -z4 `find . -type f -not -path "./_build/*" -name "*.png"`
``
step of the instructions in the [contributing guide](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/docs/contributing/docs.rst). If this isn't too basic, and you're interested in merging, let me know and I'd be happy to fiddle with the image compression a bit more. 

Thanks!

### CODE REVIEW

**Comment by choldgraf** [comment]
Thanks for the contribution! I agree that information on resizing a VM would be quite useful. My biggest question is: what of this should be in a DO-specific section, vs a provider-agnostic section. E.g. a lot of this PR adds info for commands like `df` that you could run on any provider...perhaps those could be in a separate page, and then the DO-specific stuff could just focus on using their interface to resize?

**Comment by wrightaprilm** [comment]
That's a good question - I struggled a little bit with where to put this. I think the resizing itself is covered well in the section on configs. But when I think about communicating how to set something like this up to colleagues ... I realize I'm likely to be higher on the scale of "technical, and willing to read the whole manual" than many of them probably are. So bringing that out more explicitly than it was was what I aimed for here.

I think having a separate "tell TLJH you've resized, and verify that it worked" page, and then interface specific instructions on each interface's install page, is a completely reasonable way to approach the issue. In which case, steps one and two could be left on the DO page, but 3-5 linked as a separate page. 

I'd be happy to do that, so let me know. You also have write access to this PR if you wanted to make a template but have me populate it.

**Comment by choldgraf** [comment]
I'd say feel free to have a go at it, and I'm happy to take a look! It'll be a day or two before I have a chance to give this a shot, just FYI. If you're short on time as well, I'd also be +1 on just merging this and opening an issue that we can take care of later.

**Comment by wrightaprilm** [comment]
No problem - I'll probably get to this sometime mid next week. I'm in no rush, and my landing from maternity leave has been a little bumpier than I thought.

**Comment by choldgraf** [comment]
cool - 3 quick thoughts:

1. I am 100% in support of peanuts gifs in issues
2. no hurry! if you think it'd be better to merge first and iterate later, just lemme know!
3. congrats on maternity :-D

**Comment by wrightaprilm** [comment]
Thanks! And wouldn't you know it - I commit to doing this around midweek, then both kids sleep a solid 12-hour night, letting me do some fun stuff.

I've added two commits that split the documentation between a resize document in howto, and a tag at the end of Digital Ocean with the image of what to look for in the DO control panel. What would be nice to be able to do in the text of resize.rst would be to link to the specific headers in the tljh-config document pertaining to resizes. I might have missed it in the contributing docs, and I wasn't sure if "too many" anchors becomes a problem in Sphinx/for y'all. But I made a branch on [my fork](https://github.com/Paleantology/the-littlest-jupyterhub/blob/anchors/docs/topic/tljh-config.rst) with a proposed anchor structure in the tljh-config document. If it looks OK, I'm happy to make a PR.

**Comment by choldgraf** [comment]
re: enabling notebook or lab extensions, I think that's a good idea for sure! many people just use the GUI so I think this would be quite nice :-)

**Comment by choldgraf** [comment]
oh and re: anchors etc, I think it's totally fine to have more anchors than less - cross-linking is super helpful in sphinx!

**Comment by choldgraf** [comment]
(lemme know if you wanna push to this PR or open new ones)

**Comment by wrightaprilm** [comment]
OK, here's what I did: 

- Merged my anchor redesign branch into master
- Made a couple edits in the resize rst to make use of the new anchors.
- I think it's done, so if you're happy with it, I'm happy with it.



I'll send a separate PR in a few days with a note on extensions (my #FOSSFriday is basically over). Do you think that ought to be its own document, or a line after the [software install](https://the-littlest-jupyterhub.readthedocs.io/en/latest/install/custom-server.html#step-3-install-conda-pip-packages-for-all-users) on the various install pages?

**Comment by choldgraf** [comment]
woot! I'll give these steps a run this week and will get back with my experience!

quick question: for the tags, you have only *added* tags, right? Not changed a pre-existing tag? Thanks for putting in the time! :-)

**Comment by wrightaprilm** [comment]
Correct, there was only one anchor in the file, on line one (.. _topic/tljh-config:). It's still there.

**Comment by choldgraf** [comment]
Hey @wrightaprilm ! I had a moment to go through these instructions, and they generally worked great! Thanks for putting together these steps :-)

I just pushed a set of edits/additions to your PR. Mind taking a look and letting me know if you're OK with those changes? If so, then I think we can merge! The main things I did were:

* Added a few more steps to the DO resizing section
* Added some more cross-links to make the content more discoverable
* Cleaned up some language here and there

Woo!

**Comment by wrightaprilm** [comment]
Looks awesome!

Teamwork!

**Comment by choldgraf** [comment]
wohoo! thanks for the great contribution @wrightaprilm , and thanks for being patient with the reviews! 🎉 🎉 🎉

**Comment by wrightaprilm** [comment]
No prob! I feel [really strongly](https://paleantology.com/2018/09/05/plan-c/) about this project - thanks for all you do!

**Comment by choldgraf** [comment]
ahh that writeup makes us feel the <3 ... thanks for sharing your thoughts, and for taking the time to improve the project :-)

**Comment by wrightaprilm** [comment]
I realized we left one thing hanging - if I were to send a PR with notes on enabling Jupyter extensions, do you think that would work best as its own doc under howto/admin, or as a line on each set-up page following the instructions for installing packages?

thx!

**Comment by choldgraf** [comment]
I think `howto/admin` would be best, since it's the same workflow for each provider!

**Pull request merged**
