### PR TITLE
Use idle culler from jupyterhub-idle-culler package

### PR DESCRIPTION
**Pull request by yuvipanda**
The idle culler lives as a script in at least 3 different
places:

- In the JupyterHub repo, as an 'example'
  https://github.com/jupyterhub/jupyterhub/tree/d126baa443ad7d893be2ff4a70afe9ef5b8a4a1a/examples/cull-idle
- In the TLJH repo, as a core part of the service
  https://github.com/jupyterhub/the-littlest-jupyterhub/blob/01ba34857dd4e316d839034ae2b3cc400b929964/tljh/cull_idle_servers.py.
  This is an import from a specific version of the JupyterHub repo,
  and has had a couple of changes made to it since.
- In the z2jh repo, as a core part of the service
  https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/c3f3be25f8ae6c72d02f385f41983b70ee1d416e/jupyterhub/files/hub/cull_idle_servers.py
  This is also an import from a specific version of the JupyterHub
  repo, but has had a lot more work done on it. Most had been sync'd
  back the JupyterHub repo, but some had not been. See
  https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commits/9c15a42b1227f3b54826f273f1689e4dc8c8e12e/images/hub/cull_idle_servers.py
  and https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commits/master/jupyterhub/files/hub/cull_idle_servers.py

The idle culler is a core integral part of every JupyterHub deployment
these days. It would be great if it was maintained separately on
its own, without being split across multiple repos.

The latest changes had been to the version in the JupyterHub repo, so I
copied it (while preserving commit history, because credit is important)
to a new repository: https://github.com/yuvipanda/jupyterhub-idle-culler

I looked through z2jh and tljh copies, and cherry-picked the following
changes manually

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/ae80fb516337b653306aa4a74f4118a38c3cb3f6
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/836f19a4c7445f3dc32120c892873275ff870d1a
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/a0787c64f19550ec96f2e06a3d7079e029fc6465
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/b230ef8156924e25368e7abf2174a9d1edf99c55
https://github.com/jupyterhub/the-littlest-jupyterhub/commit/20374db7c6ce2934ce700873b9d1225929e29456#diff-f00cd100e9f673285208aaa6fc0c3212

There were a few from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commits/9c15a42b1227f3b54826f273f1689e4dc8c8e12e/images/hub/cull_idle_servers.py
I could not apply, but mostly because those features had been
re-implemented already.

Right now, the package is a direct port of the code we had. Once
this settles in, I am hopefull we can iterate faster and make cool
new changes.

 - [x] Add / update documentation
 - [x] Add tests

### CODE REVIEW

**Comment by yuvipanda** [comment]
If all tests pass, I will make a release of the idle culler and reference that instead of the git url

**Comment by yuvipanda** [comment]
Similar PR in z2jh: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1648

**Comment by yuvipanda** [comment]
I'll probably move the repo to the JupyterHub org once a few people agree.

**Comment by GeorgianaElena** [comment]
@yuvipanda, unfortunately the upgrade test is failing often when building jupyterlab :( (`jupyterlab build` command is ran 2 times in this tests). I think this is what happened with the integration test before increasing the min memory. However, [this comment](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/518#issuecomment-602630492) says that the 1GB memory might sometimes not be enough even for installation, so I'm confused :confused:  

Also, part of the solution in the past was [this PR](https://github.com/jupyterhub/the-littlest-jupyterhub/pull/499).

**Comment by yuvipanda** [comment]
yeah, 2G fixes it :( I'm trying 1.5G. 

See https://github.com/jupyterlab/jupyterlab/issues/4824 for prior work

**Comment by yuvipanda** [comment]
Looks like I just didn't restart the tests enough times at 1G! I'm going to remove all the commits I made moving the memory limit around.

This is ready to merge! \o/

**Comment by yuvipanda** [comment]
hmmm, so it fails now but succeeds if I make a few commits that eventually bring the memory requirement to 1G?

**Comment by GeorgianaElena** [comment]
@yuvipanda, I've restarted the tests and now they pass again :confused:

**Comment by GeorgianaElena** [comment]
I think we should merge this PR as it's a great addition :heart: and open an issue about the tests failing intermittently again (:disappointed:)
WDYT?

**Comment by yuvipanda** [comment]
@GeorgianaElena ah, damn - re: intermittent. At least that makes more sense and I'm not going bananas...

Would love to get this merged and open another issue for the flaky tests!

**Comment by consideRatio** [comment]
Things seem to work as intented in the Z2JH project from what I can tell after trying it, and the changes look good to me! Merging given Georgianas approval!

**Comment by yuvipanda** [comment]
Thanks, @GeorgianaElena and @consideRatio!

**Pull request merged**
